### ISSUE TITLE
Breaklines can't be used

### ISSUE THREAD

**Issue by meaz** [Ajnasz/hubot-respond#7]
If you use a breakline in the command, then the answer gets cut to this brealine.
Example:
```
me> hubot respond to test with This is a long text.
And this is a second line.
hubot> Respond added
me> test
hubot> This is a long text.
```
"And this is a second line." is not added.

**Comment by Ajnasz** [comment]
Should be fixed, please check `hubot-respond@v1.2.1`

**Comment by meaz** [comment]
sorry, it doesn't fix it.
I'm using that in an xmpp room. In the stanza, I get
<body>line 1
Line 2</body>
SO I don't know if that it is really a line break

**Comment by Ajnasz** [comment]
Hey. Can you create a test case in https://github.com/Ajnasz/hubot-respond/blob/master/test/index-test.js which breaks, then easier to fix it.  :)

**Comment by meaz** [comment]
I'm waiting for some outside help on this, and if I get some, I'll add the info.
